version: 2.1

orbs:
  node: circleci/node@3

jobs:
  build:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test:unit
          environment:
            NODE_ENV: development

workflows:
  ci:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
